// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOc5RkFxYCuhwpzk5ywU7Z7pz7er1ABLg',
    appId: '1:771315232809:web:6258e8fc8cdad0c63dec38',
    messagingSenderId: '771315232809',
    projectId: 'expense-tracker-flutter-38ad6',
    authDomain: 'expense-tracker-flutter-38ad6.firebaseapp.com',
    storageBucket: 'expense-tracker-flutter-38ad6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSXqHfHj7z68vHgT3J19o5Li0nK44hOU',
    appId: '1:771315232809:android:eb0b15aa8eca20b13dec38',
    messagingSenderId: '771315232809',
    projectId: 'expense-tracker-flutter-38ad6',
    storageBucket: 'expense-tracker-flutter-38ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1NsU84KcFb5Ai1coUZ5ZJQebQZSTgfg',
    appId: '1:771315232809:ios:dd66a4c4390b6c983dec38',
    messagingSenderId: '771315232809',
    projectId: 'expense-tracker-flutter-38ad6',
    storageBucket: 'expense-tracker-flutter-38ad6.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1NsU84KcFb5Ai1coUZ5ZJQebQZSTgfg',
    appId: '1:771315232809:ios:6155eaded1c1d09d3dec38',
    messagingSenderId: '771315232809',
    projectId: 'expense-tracker-flutter-38ad6',
    storageBucket: 'expense-tracker-flutter-38ad6.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp.RunnerTests',
  );
}
